#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time machine

title: Felipe Gonzalez's [fgonzcat]
logo: /assets/img/felipe4-bg.png
description: "PhD in Physics"
#show_downloads: true
baseurl: ""
url: "https://www.gnm.cl/fgonzalez"
date_format: "%b %-d, %Y"

# Optional features
show_related_posts: True
show_post_footers: True
show_subscribe_cta: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: fgonzcat
stackoverflow_id:
linkedin_username: felipe-gonzalez-a6a96626

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true

