#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine


title: Felipe Gonzalez [fgonzcat]
logo: "/assets/img/felipe4-bg.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD in Physics.
  <br><br>  
  A condensed matter physist investigating the the mysteries of Planetary Interiors.  Find my code sources in my GitHub profile!
  <br><br>     Email: "f_gonzalez@berkeley.edu" <br><br>    <img src="https://companieslogo.com/img/orig/CLVT-be02c47f.png" width="20"><a href="https://www.webofscience.com/wos/author/rid/G-3660-2014" target="_blank">Web of Science</a> 
  <br>     <img src="https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg" width="20"><a href="https://www.instagram.com/felipegonzalezcataldo/" target="_blank">@felipegonzalezcataldo</a>
  <br>      <a href="https://www.linkedin.com/in/johnodonnell93"><i class="icon fa fa-linkedin-square" aria-hidden="true">View LinkedIn Profile</a>   
  
theme: jekyll-theme-minimal
classes: wide
